"""Add is_verified and verification_token to User model

Revision ID: 02617d156732
Revises: 684b61c868a5
Create Date: 2025-09-05 23:04:50.617450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02617d156732"
down_revision: Union[str, Sequence[str], None] = "684b61c868a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connections",
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column("connections", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "organizations",
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "organizations", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("verification_token", sa.UUID(), nullable=True))
    op.add_column("users", sa.Column("password_reset_token", sa.UUID(), nullable=True))
    op.add_column(
        "users", sa.Column("password_reset_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column("users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, "users", ["verification_token"])
    op.create_unique_constraint(None, "users", ["password_reset_token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("users", "password_reset_expires_at")
    op.drop_column("users", "password_reset_token")
    op.drop_column("users", "verification_token")
    op.drop_column("users", "is_verified")
    op.drop_column("organizations", "updated_at")
    op.drop_column("organizations", "created_at")
    op.drop_column("connections", "updated_at")
    op.drop_column("connections", "created_at")
    # ### end Alembic commands ###
