"""add agent_id to connections

Revision ID: 20250127_add_agent_id
Revises: 20250127_production_ready_improvements
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250127_add_agent_id'
down_revision = '20250127_prod'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('agent_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_connections_agent_id'), 'connections', ['agent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connections_agent_id'), table_name='connections')
    op.drop_column('connections', 'agent_id')
    # ### end Alembic commands ###
