"""add db_name column to connections

Revision ID: 5b56126de0f
Revises: 02617d156732
Create Date: 2025-01-07 01:58:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b56126de0f"
down_revision = "02617d156732"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "connections", sa.Column("db_name", sa.String(), nullable=False, server_default="Unknown")
    )
    op.alter_column("connections", "db_name", server_default=None)
    op.alter_column("connections", "db_type", server_default="SQL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("connections", "db_type", server_default="POSTGRESQL")
    op.drop_column("connections", "db_name")
    # ### end Alembic commands ###
